// companyData.ts
export const companyData = [
    { id: 1, name: "Tesla", websiteUrl: 'https://roic.ai/company/TSLA', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 2, name: "ASML", websiteUrl: 'https://roic.ai/company/ASML', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 3, name: "LVMH", websiteUrl: 'https://roic.ai/company/LVMH', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 4, name: "Nvidia", websiteUrl: 'https://roic.ai/company/NVDA', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 5, name: "Snowflake", websiteUrl: 'https://roic.ai/company/SNOW', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 6, name: "Crowdstrike", websiteUrl: 'https://roic.ai/company/CRWD', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 7, name: "ZScaler", websiteUrl: 'https://roic.ai/company/ZS', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 8, name: "Datadog", websiteUrl: 'https://roic.ai/company/DDOG', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 9, name: "Cloudflare", websiteUrl: 'https://roic.ai/company/NET', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 10, name: "Confluent", websiteUrl: 'https://roic.ai/company/CFLT', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 11, name: "MongoDB", websiteUrl: 'https://roic.ai/company/MDB', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 12, name: "GitLab", websiteUrl: 'https://roic.ai/company/GTLB', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 13, name: "SentinelOne", websiteUrl: 'https://roic.ai/company/S', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 14, name: "Airbnb", websiteUrl: 'https://roic.ai/company/ABNB', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 15, name: "Lululemon", websiteUrl: 'https://roic.ai/company/LULU', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 16, name: "Blackrock", websiteUrl: 'https://roic.ai/company/BLK', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 17, name: "Ulta Beauty", websiteUrl: 'https://roic.ai/company/ULTA', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 18, name: "Dutch Bros", websiteUrl: 'https://roic.ai/company/BROS', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 19, name: "Twilio", websiteUrl: 'https://roic.ai/company/TWLO', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 20, name: "Waste Management", websiteUrl: 'https://roic.ai/company/WM', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 21, name: "Livent", websiteUrl: 'https://roic.ai/company/LTHM', logoUrl: 'https://roic.ai/company/TSLA' },
    { id: 22, name: "Lockheed Martin", websiteUrl: 'https://roic.ai/company/LMT', logoUrl: 'https://roic.ai/company/TSLA' },
];
