import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import CompanyList from './components/CompanyList'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio Holdings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <CompanyList />
      </main>
    </>
  )
}
